### PR TITLE
Fix font issue in Kali

### PR DESCRIPTION
**Pull request by daniruiz**
Kali uses qt5ct to configure themes and fonts for qt apps. The font set has priority by the one set in havoc's code.
If you override the variable QT_QPA_PLATFORMTHEME and run havoc client by the command `QT_QPA_PLATFORMTHEME= havoc client` the issue isn't pressent.

I found that by setting the font in Havoc.qss this is respected by qtct

The package in Kali already provides a patch to fix this for now https://gitlab.com/kalilinux/packages/havoc/-/blob/kali/master/debian/patches/fix-monospace-font.patch?ref_type=heads

### CODE REVIEW

**Comment by daniruiz** [comment]
> hey there, can you target the dev branch?

Done, sorry I didn't realize I did it against main branch

**Comment by daniruiz** [comment]
At the same time, there are other small patches in Kali to make it work with the packaging
https://gitlab.com/kalilinux/packages/havoc/-/tree/kali/master/debian/patches?ref_type=heads
  
Not all of them have to be copied to upstream, but just in case they help.
The most important ones are the patches that move the data folder paths to the user's home directory, in order to be able to write files into it, as the tool is installed under /usr/share/ by the package.

**Comment by S4ntiagoP** [comment]
I actually like your solution better, given that it doesn't rely on timers, please feel free to replace the current approach with your own

**Comment by daniruiz** [comment]
I've created another MR with a better solution https://github.com/HavocFramework/Havoc/pull/425

**Pull request closed without merging**
