### PR TITLE
fix grammatical error 🤡

### PR DESCRIPTION
**Pull request by gatariee**
Hello, my dear. I've noticed a small grammatical mistake. It caught my attention while I was attempting to take a screenshot of my grandmother's desktop.

Please employ the use of [grammarly](https://www.grammarly.com/) in your development process.

### CODE REVIEW

**Comment by Cracked5pider** [comment]
is your granny single? thanks for the PR. silly me I should have learned english first.

**Comment by gatariee** [comment]
my grandpa passed away a couple years ago, i believe she is looking for hot Austrian men, do you know anyone who may be eligible?

**Comment by Cracked5pider** [comment]
zamn

**Comment by pengsies** [comment]
image

**Pull request merged**
