### PR TITLE
complete some functions in ObjectApi.c

### PR DESCRIPTION
**Pull request by zesiar0**

### CODE REVIEW

**Comment by Cracked5pider** [comment]
I uselly dont use stdio functions like malloc, memset or strlen. I wrote functions for these operations like:
for malloc use ``Instance->Win32.LocalAlloc`` 
for strlen use ``StringLengthA`` 
memset use ``MemSet``

**Comment by Cracked5pider** [comment]
my bad i miss clicked the close button.

**Comment by zesiar0** [comment]
> I usually don't use stdio functions like malloc, memset or strlen. I wrote functions for these operations like: for malloc use `Instance->Win32.LocalAlloc` for strlen use `StringLengthA` memset use `MemSet`

ok, i got it

**Comment by zesiar0** [comment]
> Hello @zesiar0, cool work! would you mind targeting the `dev` branch?

Yeah

**Comment by S4ntiagoP** [comment]
I think I can do it, let me try

**Comment by zesiar0** [comment]
> I think I can do it, let me try

So, if i want to contribute later, i need to submit code to the `dev` branch, right?

**Comment by S4ntiagoP** [comment]
yup, always to dev.

**Comment by S4ntiagoP** [comment]
Ok, I could not merge, my git skillz are fairly limited...
I just pushed the code to dev directly, thank you so much for contributing!

**Pull request closed without merging**
