### PR TITLE
Update CONTRIBUTING.MD

### PR DESCRIPTION
**Pull request by 5h611in9f0rd**
kali linux user fix error

### CODE REVIEW

**Comment by S4ntiagoP** [comment]
target  the `dev` branch plz

**Comment by 5h611in9f0rd** [comment]
> `dev`지점 plz를 대상으로

**Comment by 5h611in9f0rd** [comment]
> target the `dev` branch plz
I'm new to GitHub, so I don't know how

**Comment by Cracked5pider** [comment]
not gonna add kali qt5 websocket error fix to the CONTRIBUTION.MD file.

**Pull request closed without merging**
